server:
  port: 8080

spring:
  application:
    name: api-gateway
  main:
    allow-bean-definition-overriding: true
  cloud:
    gateway:
      globalcors:
        cors-configurations:
          '[/**]':
            allowedOrigins:
              - "http://localhost:3000"
              - "http://127.0.0.1:3000"
            allowedMethods:
              - GET
              - POST
              - PUT
              - DELETE
              - OPTIONS
            allowedHeaders:
              - "*"
            allowCredentials: true
            maxAge: 3600
      # Removed conflicting routes - let Java configuration handle them
      routes:
        - id: kafka-ui
          uri: http://kafka-ui:8080
          predicates:
            - Path=/kafka-ui/**
          filters:
            - RewritePath=/kafka-ui/(?<segment>.*), /${segment}
        - id: keycloak-admin
          uri: http://localhost:8089
          predicates:
            - Path=/auth/admin/**
          filters:
            - RewritePath=/auth/admin/(?<segment>.*), /admin/${segment}

  data:
    redis:
      host: redis
      port: 6379
      password: redispass
      timeout: 2000ms

  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: api-gateway-group

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8089/realms/parcel-realm

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

resilience4j:
  circuitbreaker:
    instances:
      authService:
        registerHealthIndicator: true
        slidingWindowSize: 10
        minimumNumberOfCalls: 5
        waitDurationInOpenState: 10000
        failureRateThreshold: 50

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha
    urls:
      - url: /api-docs/auth-service
        name: Auth Service
      - url: /api-docs/pricing-service
        name: Pricing Service
      - url: /api-docs/payment-service
        name: Payment Service
      - url: /api-docs/parcel-service
        name: Parcel Service
      - url: /api-docs/consolidation-service
        name: Consolidation Service
      - url: /api-docs/warehouse-service
        name: Warehouse Service
      - url: /api-docs/eta-service
        name: ETA Service
      - url: /api-docs/chatbot-service
        name: Chatbot Service

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics,gateway
  endpoint:
    health:
      show-details: always
  tracing:
    sampling:
      probability: 1.0

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
    com.parcel.apigateway: DEBUG