server:
  port: 8083

spring:
  application:
    name: auth-service
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: ${KEYCLOAK_ISSUER_URI:http://localhost:8080/realms/parcel-realm}

keycloak:
  auth-server-url: ${KEYCLOAK_URL:http://localhost:8080}
  realm: ${KEYCLOAK_REALM:parcel-realm}
  resource: ${KEYCLOAK_CLIENT:auth-service}
  credentials:
    secret: ${KEYCLOAK_SECRET:your-client-secret}
  admin:
    username: ${KEYCLOAK_ADMIN_USER:admin}
    password: ${KEYCLOAK_ADMIN_PASSWORD:admin}

springdoc:
  api-docs:
    path: /api-docs
    enabled: true
  swagger-ui:
    path: /swagger-ui.html
    display-request-duration: true
    tags-sorter: alpha
    operations-sorter: alpha
    url: /api-docs
    config-url: /api-docs/swagger-config
    urls-primary-name: Auth Service API
    disable-swagger-default-url: false

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

logging:
  level:
    com.sparrow.authservice: DEBUG
    org.keycloak: INFO
    org.springdoc: INFO


management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
      base-path: /management
  endpoint:
    health:
      show-details: always
    metrics:
      enabled: true
    info:
      enabled: true