# Application Configuration
spring:
  application:
    name: auth-service
  
  # Database Configuration (for user management)
  datasource:
    url: jdbc:h2:mem:authdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:

  # JPA Configuration
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: create-drop  # Use 'update' in production
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  # Spring Security OAuth2 Resource Server Configuration
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://keycloak:8080/realms/parcel-realm
          jwk-set-uri: http://keycloak:8080/realms/parcel-realm/protocol/openid-connect/certs

  # Web Configuration
  web:
    resources:
      add-mappings: false

  # Jackson Configuration for Keycloak compatibility
  jackson:
    deserialization:
      fail-on-unknown-properties: false  # Critical for Keycloak version compatibility
    serialization:
      fail-on-empty-beans: false
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: UTC
    default-property-inclusion: non_null

  # Eureka Client Configuration
  cloud:
    loadbalancer:
      enabled: true

  # Actuator Configuration
  management:
    endpoints:
      web:
        exposure:
          include: health,info,metrics,env,beans,prometheus
    endpoint:
      health:
        show-details: always
        show-components: always
      metrics:
        enabled: true
    health:
      circuitbreakers:
        enabled: true
      defaults:
        enabled: true

  # Logging Configuration
  logging:
    level:
      com.sparrow.auth: DEBUG
      org.springframework.security: DEBUG
      org.keycloak: DEBUG
      org.hibernate.sql: DEBUG
      org.hibernate.type: TRACE
      io.github.resilience4j: DEBUG
    pattern:
      console: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

# Server Configuration
server:
  port: 8083
  servlet:
    context-path: /
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

# Eureka Client Configuration
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka-server:8761/eureka/
    healthcheck:
      enabled: true
  instance:
    prefer-ip-address: true
    instance-id: ${spring.application.name}:${spring.application.instance-id:${random.value}}
    hostname: auth-service
    appname: auth-service
    status-page-url-path: /actuator/info
    health-check-url-path: /actuator/health

# Keycloak Configuration
keycloak:
  # Standard Keycloak properties
  auth-server-url: http://keycloak:8080
  realm: parcel-realm
  resource: auth-service
  credentials:
    secret: auth-service-secret

  # Admin configuration
  admin:
    username: admin
    password: admin123

  # Alternative configuration names for compatibility
  url: http://keycloak:8080
  client:
    id: auth-service
    secret: auth-service-secret

  # Token Configuration
  token:
    expiration: 3600  # 1 hour
    refresh-expiration: 7200  # 2 hours

  # Connection Configuration
  connection:
    pool-size: 20
    connection-timeout: 30000
    socket-timeout: 30000

# Security Configuration
security:
  jwt:
    secret: your-jwt-secret-key-here-change-in-production  # Change this in production
    expiration: 86400000  # 24 hours
    issuer: auth-service

# Resilience4j Configuration
resilience4j:
  circuitbreaker:
    instances:
      keycloakClient:
        register-health-indicator: true
        sliding-window-type: COUNT_BASED
        sliding-window-size: 10
        minimum-number-of-calls: 5
        wait-duration-in-open-state: 10s
        permitted-number-of-calls-in-half-open-state: 3
        failure-rate-threshold: 50
        event-consumer-buffer-size: 10
        record-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.ConnectException
          - jakarta.ws.rs.ProcessingException
          - java.util.concurrent.TimeoutException

  retry:
    instances:
      keycloakRetry:
        max-attempts: 3
        wait-duration: 2s
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
        retry-exceptions:
          - org.springframework.web.client.ResourceAccessException
          - java.net.ConnectException
          - jakarta.ws.rs.ProcessingException

  timelimiter:
    instances:
      keycloakTimeout:
        timeout-duration: 30s
        cancel-running-future: true

# Feign Client Configuration
feign:
  client:
    config:
      default:
        connect-timeout: 5000
        read-timeout: 5000
        logger-level: basic
  circuitbreaker:
    enabled: true

# Spring Doc OpenAPI Configuration
springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tags-sorter: alpha
    operations-sorter: alpha
  packages-to-scan: com.sparrow.auth.controller
  default-produces-media-type: application/json
  show-actuator: true

# Custom Application Properties
app:
  version: 1.0.0
  name: Auth Service
  description: Authentication and Authorization Microservice

  keycloak:
    connection:
      max-retries: 10
      initial-delay-ms: 5000
      max-delay-ms: 30000
    admin:
      client-id: admin-cli
      realm: master

  rate-limiting:
    enabled: true
    requests-per-second: 100

# H2 Database Console (for development only)
h2:
  console:
    enabled: true
    path: /h2-console
    settings:
      trace: false
      web-allow-others: false