server:
  port: 8090

spring:
  application:
    name: payment-service
  data:
    mongodb:
      uri: mongodb://admin:password@mongodb:27017/payment_db?authSource=admin
  kafka:
    bootstrap-servers: kafka:9092
    consumer:
      group-id: payment-group
    properties:
      spring.json.trusted.packages: "*"

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html
    tags-sorter: alpha
    operations-sorter: alpha

eureka:
  client:
    service-url:
      defaultZone: http://eureka-server:8761/eureka/

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics
  endpoint:
    health:
      show-details: always